name: Wake Website

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Run Browser
        run: node index.js
